### ISSUE TITLE
Separate option for resetting AFK status on mouse click

### ISSUE THREAD

**Issue by Aecority** [sakura-ryoko/afkplus#28]
**Lack of functionality to disable removal of AFK status on mouse click**
Raid farms and most XP farms require the player to setup an autoclicker to run them while afk. It's frustrating that there is no way to tell whether a player is online or is AFK and running this farm of this type. There are already options like `resetOnMovement` and `resetOnLook`, but attacks always remove the AFK status

**Solution**
Addition of an option in the config file named something like `resetOnClick` that when set to true, will check for clicks and remove the AFK status if a click is detected, and when set to false, will not check for clicks.

**Comment by sakura-ryoko** [comment]
That is a vanilla function that resets the lastPlayerAction value

**Comment by sakura-ryoko** [comment]
It might not be exactly as you've stated, but I was able to add functionality to mark players as AFK while they are "ONLY" attacking, and not moving; such as being stationary with an auto clicker.

**Comment by Aecority** [comment]
> It might not be exactly as you've stated, but I was able to add functionality to mark players as AFK while they are "ONLY" attacking, and not moving; such as being stationary with an auto clicker.

Okay, thanks for helping!

**Comment by sakura-ryoko** [comment]
Yeah so the feature basically works by measuring "move / look / attack" update status timers being tracked separately; and compares the 4 data points.

So basically, if the Auto Clicking player does `Anything` like accidentally picking up items; or have any sort of changes in looking or even micro movements; then this change will not take effect; because those values are required for the detection to work properly.

In this case; if the detection is positive; then it ignores the Vanilla `lastUpdateTimer` which AFK mods use for AFK detection.
But, like I said; the moment they have any micro movements ... which is something that people might be able to do; then this code wouldn't work; and marks them as Not AFK.

This feature also has an interesting side effect of potentially marking them as Invulnerable while using a farm; or if Auto Kick is enabled; then it might Auto Kick them also; potentially breaking a farm.
